### ISSUE TITLE
Extrude a polygon to a solid

### ISSUE THREAD

**Issue by happydpc** [mkeeter/fidget#105]
I am trying to implement an extrusion of a polygon face, how to make it happen? thanks.

**Comment by mkeeter** [comment]
This question isn't specific enough to provide an answer.

If you're looking for the mathematics, you can reference the `libfive` implementations of [`polygon`](https://github.com/libfive/libfive/blob/4c59b11667bbe8be9802f59697fa64bbfe1ea82d/libfive/stdlib/stdlib_impl.cpp#L135C6-L144) and [`extrude_z`](https://github.com/libfive/libfive/blob/4c59b11667bbe8be9802f59697fa64bbfe1ea82d/libfive/stdlib/stdlib_impl.cpp#L373).

Please provide details on what you're trying to do, including specific code that you've written.

**Comment by happydpc** [comment]
I want to make an arbitrary polygon with some points, the libfive is a polygon made by a center and specific angle. I want to make a CAD application with a boolean operation including extrusion and revolution solids.

**Comment by mkeeter** [comment]
Fidget (and `libfive` before it) use implicit surfaces, so you need to find a way to convert your polygon to a pure mathematical equation representing (signed) distance to the polygon's boundary.

[Here's one way to do it for Bézier curves](https://www.shadertoy.com/view/dls3Wr).  This example is using GLSL, so you'd have to translate the logic into the operators supported by Fidget.  On the bright side, distance-to-a-line-segment is much easier than distance-to-a-Bézier-curve!

For now, I'm going to close this issue, because it's not Fidget-specific.  When you have reached the point of using the Fidget library, feel free to reopen it.
