### ISSUE TITLE
Representation of sets of variables

### ISSUE THREAD

**Issue by waywardmonkeys** [mkeeter/fidget#182]
The functions `ShapeTracingEval::eval_v` and `ShapeBulkEval::eval_v` both take a hash map: `HashMap<VarIndex, V>` but this is not used as an actual hash map (apart from test code setting it up), and it is iterated over:

```
        for (var, value) in vars {
            if let Some(i) = vs.get(&Var::V(*var)) {
                if i < self.scratch.len() {
                    self.scratch[i].copy_from_slice(value);
                } else {
```

This could probably take a `&[(VarIndex, V)]` instead and save on some allocations and overhead.

Similar is true for some other `eval` functions, although they do make minor use of the hash map APIs. (But how many variables are typical or expected?)

Finally, `VarMap` says that:

```
/// Map from [`Var`] to a particular index
///
/// Variable indexes are automatically assigned the first time
/// [`VarMap::insert`] is called on that variable.
///
/// Indexes are guaranteed to be tightly packed, i.e. a map `vars` will contains
/// values from `0..vars.len()`.
///
/// For efficiency, this type does not allocate heap memory for `Var::X/Y/Z`.
#[derive(Default, Serialize, Deserialize)]
pub struct VarMap {
    x: Option<usize>,
    y: Option<usize>,
    z: Option<usize>,
    v: HashMap<VarIndex, usize>,
}
```

How many variables are common though? Would this be more efficient in memory and time with a linear search?

This is mainly a point of curiosity right now as I look through things.

**Comment by mkeeter** [comment]
In this case, using a hashmap is for its invariants, rather than performance: it's an implicit assertion that variable will only be defined once.  If we passed in a slice, it would be possible to provide invalid inputs (multiple values for the same variable), so we'd need to check that and return an error.

I'm looking at adding a `ShapeVars` wrapper object that enforces those invariants while hiding the inner data type (so it could be switched to a `Vec` under the hood).
